# Configured by ansible
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
ZSH_THEME="agnoster"
plugins=(battery docker fedore git go )

source $ZSH/oh-my-zsh.sh
