---
# Git playbook

- name: Install git package
  become: yes
  become_method: sudo
  dnf:
    name: git
    state: latest
  when: ansible_distribution == 'Fedore'

- name: Install git package
  homebrew:
    name: git
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: Configure git package
  template:
    src: gitconfig
    dest: "{{ home_dir }}/.gitconfig"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0600

- name: Create repositories directory
  file:
    path: "{{ git.repo_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0750
