---
# Atom playbook
- block:
  - name: Download atom editor rpm
    get_url:
      url: https://atom.io/download/rpm
      dest: "{{ tmp_dir }}/atom.rpm"

  - name: Install atom editor
    become: yes
    become_method: sudo
    dnf:
      name: "{{ tmp_dir }}/atom.rpm"
      state: present
  when: ansible_distribution == 'Fedora'

- name: install from brew cask
  homebrew_cask:
    name: atom
    state: present
  when: ansible_distribution == 'MacOSX'

- name: Update all installed plugins
  shell: >
    apm upgrade -compatible --no-confirm | grep -E '(empty)'
    && echo 'No update.'
  register: apm_update_result
  changed_when: "'No update.' not in apm_update_result.stdout"

- name: Install atom package
  shell: >
    apm list --bare | grep -E '^{{ item }}@'
    && echo 'Already installed.'
    || apm install '{{ item }}'
  with_items:
    - "{{ atom.packages }}"
  register: apm_install_result
  changed_when: "'Already installed.' not in apm_install_result.stdout"

- name: Install ansible-lint
  block:
    - name: Install on Fedora
      package:
        name: python3-ansible-lint
        state: latest
      when: ansible_distribution == 'Fedora'
    - name: Install on Mac
      homebrew:
        name: ansible-lint
        state: present
      when: ansible_distribution == 'MacOSX'
  when: "'linter-ansible-linting' in atom.packages"

- name: Install ansible-lint
  block:
    - name: Fedora
      package:
        name: golint
        state: latest
      when: ansible_distribution == 'Fedora'
  when: "'go-plus' in atom.packages"
