---
# Terminator playbook

- name: Install terminator package
  become: yes
  become_method: sudo
  dnf:
    name: terminator
    state: latest

- name: Create config directory
  file:
    path: "{{ home_dir }}/.config/terminator/"
    state: directory

- name: Configure terminator
  template:
    src: config
    dest: "{{ home_dir }}/.config/terminator/config"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0664
