---
# Docker playbook

- name: Remove old docker version
  become: yes
  become_method: sudo
  package:
    name: 'docker'
    state: absent

- name: Add Docker GPG key.
  become: yes
  become_method: sudo
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  become: yes
  become_method: sudo
  get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Configure Docker Edge repo.
  become: yes
  become_method: sudo
  ini_file:
    dest: '/etc/yum.repos.d/docker-ce.repo'
    section: 'docker-ce-edge'
    option: enabled
    value: '0'

- name: Install Docker.
  become: yes
  become_method: sudo
  package:
    name: docker-ce
    state: present

- name: Create docker group
  become: yes
  become_method: sudo
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: yes
  become_method: sudo
  command: usermod -a -G docker {{ user }}

- name: Enable docker service
  become: yes
  become_method: sudo
  service:
    name: docker
    enabled: yes

- name: Restart Docker service
  become: yes
  become_method: sudo
  service:
    name: docker
    state: restarted
