---
# Google Chrome playbook

- name: Add chrome repository
  become: yes
  become_method: sudo
  copy:
    src: chrome.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: Install Google Chrome - stable
  become: yes
  become_method: sudo
  dnf:
    name: google-chrome-stable
    state: present
