---
# Google Chrome playbook

- name: Add chrome repository
  copy:
    src: chrome.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: Install Google Chrome - stable
  dnf:
    name: google-chrome-stable
    state: present
