---
# fonts playbook

- name: Clone powerline fonts repo
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{ tmp_dir }}/fonts"

- name: Create user fonts directory
  file:
    path: "{{home_dir }}/.local/share/fonts/"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: Install powerline fonts
  copy:
    src: "{{ tmp_dir }}/fonts/"
    dest: "{{home_dir }}/.local/share/fonts/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: Refresh font cache
  shell: fc-cache -vf
